### ISSUE TITLE
Don't give people an IPA...

### ISSUE THREAD

**Issue by ghost** [0xff7/triple_fetch#1]
Seriously. If you don't know how to click a button in Xcode, you shouldn't use this.

**Comment by 0xff7** [comment]
Agreed except not everyone has a Mac or access to Xcode which is why I compiled it for them

**Comment by ghost** [comment]
UGH... What are you smoking?

**Comment by 0xff7** [comment]
Yea you must be the one that's high cuz you're making no sense
